### ISSUE TITLE
Circular navigation setting with macro

### ISSUE THREAD

**Issue by zelytra** [zelytra/BetterFleet#160]
Some weird things on the trigger macro happen when a controller is connected and active on the PC player. French reported of the user concern :

joueur app betterfleet arrière plan windows 11
clavier souris pour se mettre lever l'ancre en focus
pas de déplacement dans le menu

quand manette, cablé
avec utilisation clavier souris
lever l'ancre -> parametre -> lever ancre -> parametre ... puis entrer

déplacement dans les menu full manette + alt tab vers better fleet premier plan fonctionne

Need investigation @dadodasyra

**Comment by dadodasyra** [comment]
When you say full controller it works. In every case ? Only in focus of betterfleet ?

**Comment by zelytra** [comment]
i tried a lot of things with my remote controller and i cant break the macro. I dont know how the user do to make it not working. Maybe caling him to see a demo may help us

**Comment by zelytra** [comment]
It happend when the param "Circular Navigation" is set to True it make failed the macro wich trigger "Rise Anchor" button

**Comment by dadodasyra** [comment]
This is a serious problem that I don't really know how to fix it.
To explain in details the issue is the setting in ATH > Circular navigation that NEEDS to be disabled in order for the macro to work.
Multiple ideas:
- Detect the setting is enabled (how ? it should be in settings file but I'm unable to find anything about it) and warn the player
  - It needs more research but since they fixed the way to change FOV from settings file I guess they protected some variables of settings so they cannot be edited without using the game itself
  - It may raise some questions about ethics/TOS about reading the file (obviously editing it would be crossing a red line so if we do this we would stay on a warning in our app)
- Warn the player in any way that it will not work with this setting available
  - This is ugly and not that good..
- Use mouse clicking instead of keyboard input for macro..
  - We need to correctly handle the window size (windows api can give the window position and size)
  - We need an api endpoint on windows to click a specific point by x,z position otherwise the user may move its mouse between moving and clicking

Currently on macro we're doing "left arrow", "left arrow" then "enter". The issue with circular navigation is that when you do left arrow but you were already focusing "drop anchor" button it loops over and get back to the session settings.
